### ISSUE TITLE
Can this code run other atari game beside breakout?

### ISSUE THREAD

**Issue by THSWind** [rlcode/reinforcement-learning#98]
I want to run other atari game, it's performance looks doesn't good. Could anyone help me?  Whether I can achieve this goal by change "gym.make('ENV_NAME')", and it's real_action? help me plllllz, appreciate so MUCH
I have changed the code like I wrote above, it's performance not so good, and occurs some ERRORS. like this:
TypeError: unsupported operand type(s) for /: 'tuple' and 'float'Traceback (most recent call last):

  File "ddqn_spaceinvaders.py", line 372, in <module>
    agent.train_replay(step)
  File "ddqn_spaceinvaders.py", line 235, in train_replay
    history[i] = np.float32(mini_batch[i][0] / 255.)

**Comment by dnddnjs** [comment]
Thanks for the report. The file/algorithm this issue references was removed or rewritten during the #122 modernization (TF/Keras → PyTorch, curated algorithm set of 9). The original code path no longer exists, so closing as no longer applicable. Feel free to reopen if you encounter a similar issue on the current PyTorch implementation.
